theme: jekyll-theme-slate
title: osu!droid Guide
domain: neroyuki.github.io  # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://neroyuki.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /osudroid-guide # place folder name if the site is served in a subfolder

defaults:
  -
    scope:
      path: "lang/vi"
      type: "pages"
    values:
      lang: "vi"