name: Update Page Metadata

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: | 
          cd helper-script
          npm install
          cd ..

      - name: Run helper script
        run: node helper-script/main.js

      # commit and push changes, if working tree is cleaned, abort and return success
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/_data/page_metadata.json
          git diff --quiet && git diff --staged --quiet ||
          git commit -m "[From Github Action] Update page metadata" && git push"


